gSystem->Load("/home/hovanes/GlueX/MCB/linux/obj/libTUserMCBIO.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/WrapperAxesCuts.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/Container.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/WrapperVirt.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/WrapperDim.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/WrapperType.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/WrapperPhysics.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/Wrapper.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/ScanPositionData.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/ScanMCB.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/mcbTreeSelector.so");
gSystem->Load("/home/hovanes/Workspaces/C++ Projects/MCB Analysis/ScanPositionPlots.so");
